spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/NoteApp
    username: postgres
    password: 4696

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true